# Generated by Django 5.2.16 on 2026-07-10 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المنطقة')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'منطقة',
                'verbose_name_plural': 'المناطق',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='رقم واتساب')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('router_name', models.CharField(blank=True, max_length=100, verbose_name='اسم الراوتر/الجهاز')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='عنوان MAC')),
                ('pppoe_username', models.CharField(blank=True, max_length=100, verbose_name='اسم مستخدم PPPoE')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر الشهري')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي'), ('suspended', 'موقوف'), ('debtor', 'مدين')], default='expired', max_length=20, verbose_name='الحالة')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='موقوف يدوياً')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribers.area', verbose_name='المنطقة')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_subscribers', to='devices.device', verbose_name='الجهاز المرتبط')),
            ],
            options={
                'verbose_name': 'مشترك',
                'verbose_name_plural': 'المشتركون',
                'ordering': ['-created_at'],
            },
        ),
    ]
