# Generated by Django 5.2.16 on 2026-07-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='pppoe_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='كلمة مرور PPPoE'),
        ),
    ]
