# Generated by Django 5.2.16 on 2026-07-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الجهاز')),
                ('device_type', models.CharField(choices=[('router', 'راوتر'), ('switch', 'سويتش'), ('access_point', 'نقطة وصول'), ('server', 'سيرفر'), ('ups', 'UPS'), ('battery', 'بطارية'), ('solar', 'جهاز شمسي')], max_length=20, verbose_name='نوع الجهاز')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='عنوان MAC')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='الرقم التسلسلي')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='اسم المستخدم')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='كلمة المرور')),
                ('status', models.CharField(choices=[('active', 'يعمل'), ('inactive', 'غير نشط'), ('maintenance', 'صيانة'), ('damaged', 'تالف')], default='active', max_length=20, verbose_name='الحالة')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الشراء')),
                ('warranty_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الضمان')),
                ('last_ping', models.DateTimeField(blank=True, null=True, verbose_name='آخر ping')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'جهاز',
                'verbose_name_plural': 'الأجهزة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ملاحظة صيانة',
                'verbose_name_plural': 'ملاحظات الصيانة',
                'ordering': ['-date'],
            },
        ),
    ]
