# Generated by Django 5.2.16 on 2026-07-10 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القالب')),
                ('template_type', models.CharField(choices=[('expiry_reminder', 'تذكير انتهاء اشتراك'), ('debt_reminder', 'تذكير دين'), ('payment_confirmation', 'تأكيد دفع'), ('maintenance_alert', 'تنبيه صيانة'), ('general', 'إعلان عام')], max_length=30, verbose_name='نوع القالب')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], default='sms', max_length=20, verbose_name='القناة')),
                ('body', models.TextField(help_text='المتغيرات المتاحة: {name}, {amount}, {expiry_date}, {phone}, {company}', verbose_name='نص الرسالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'قالب رسالة',
                'verbose_name_plural': 'قوالب الرسائل',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=50, verbose_name='المستلم')),
                ('body', models.TextField(verbose_name='نص الرسالة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('sent', 'مُرسل'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inms_messages.messagetemplate')),
            ],
            options={
                'verbose_name': 'سجل رسالة',
                'verbose_name_plural': 'سجلات الرسائل',
                'ordering': ['-created_at'],
            },
        ),
    ]
