# Generated by Django 5.2.16 on 2026-07-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inms_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='body',
            field=models.TextField(help_text='المتغيرات المتاحة: {name}, {amount}, {due_date}, {total_amount}, {phone}, {company}', verbose_name='نص الرسالة'),
        ),
    ]
