# Generated by Django 5.2.16 on 2026-07-10 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الباقة')),
                ('speed', models.CharField(max_length=50, verbose_name='السرعة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('duration_value', models.PositiveIntegerField(default=1, verbose_name='مدة الاشتراك')),
                ('duration_type', models.CharField(choices=[('day', 'يوم'), ('month', 'شهر'), ('year', 'سنة')], default='month', max_length=10, verbose_name='نوع المدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'باقة',
                'verbose_name_plural': 'الباقات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.CharField(max_length=50, verbose_name='السرعة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي'), ('suspended', 'موقوف')], default='active', max_length=20, verbose_name='الحالة')),
                ('auto_expiry', models.BooleanField(default=True, verbose_name='انتهاء تلقائي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.package', verbose_name='الباقة')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscribers.subscriber', verbose_name='المشترك')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'إنشاء'), ('renewed', 'تجديد'), ('expired', 'انتهاء'), ('suspended', 'إيقاف'), ('reactivated', 'تفعيل')], max_length=20, verbose_name='الإجراء')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='subscriptions.subscription', verbose_name='الاشتراك')),
            ],
            options={
                'verbose_name': 'سجل الاشتراك',
                'verbose_name_plural': 'سجلات الاشتراكات',
                'ordering': ['-date'],
            },
        ),
    ]
