# Generated by Django 5.2.16 on 2026-07-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='شبكة الإنترنت', max_length=200, verbose_name='اسم الشبكة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='الشعار')),
                ('currency', models.CharField(default='ILS', max_length=10, verbose_name='العملة')),
                ('currency_symbol', models.CharField(default='₪', max_length=10, verbose_name='رمز العملة')),
                ('subscription_alert_days', models.PositiveIntegerField(default=3, verbose_name='أيام تنبيه انتهاء الاشتراك')),
                ('pagination_size', models.PositiveIntegerField(default=20, verbose_name='عدد السجلات في الصفحة')),
                ('timezone', models.CharField(default='Asia/Gaza', max_length=50, verbose_name='المنطقة الزمنية')),
                ('sms_api_url', models.URLField(blank=True, verbose_name='رابط SMS API')),
                ('sms_api_key', models.CharField(blank=True, max_length=255, verbose_name='مفتاح SMS API')),
                ('sms_sender_id', models.CharField(blank=True, max_length=50, verbose_name='معرّف المرسل')),
                ('cashbox_opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='رصيد الصندوق الافتتاحي')),
                ('auto_suspend_on_expiry', models.BooleanField(default=False, verbose_name='تعليق تلقائي عند الانتهاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
    ]
