# Generated by Django 5.2.16 on 2026-07-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='sms_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم مستخدم MTC SMS'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='sms_api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='كلمة مرور MTC SMS'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='sms_api_url',
            field=models.URLField(blank=True, help_text='اتركه فارغاً لاستخدام الرابط الافتراضي: int.mtcsms.com', verbose_name='رابط إرسال SMS (اختياري)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='sms_sender_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='اسم المرسل (From)'),
        ),
    ]
