# Generated by Django 5.2.16 on 2026-07-11 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inms_messages', '0002_systemsettings_debt_sms_template'),
        ('settings_app', '0002_systemsettings_sms_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='debt_sms_template',
            field=models.ForeignKey(blank=True, help_text='يُستخدم عند إرسال تذكير دين من صفحة الديون', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inms_messages.messagetemplate', verbose_name='قالب SMS تذكير الدين'),
        ),
    ]
