# Generated by Django 5.2.16 on 2026-07-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0006_systemsettings_auto_renew_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='theme_mode',
            field=models.CharField(choices=[('system', 'حسب النظام'), ('light', 'فاتح'), ('dark', 'داكن')], default='system', max_length=10, verbose_name='الوضع الافتراضي'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='theme_primary',
            field=models.CharField(default='#6366f1', help_text='اللون العام للهوية (مثل #6366f1)', max_length=7, verbose_name='اللون الأساسي'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='theme_radius',
            field=models.CharField(choices=[('soft', 'ناعمة'), ('medium', 'متوسطة'), ('sharp', 'حادّة')], default='medium', max_length=10, verbose_name='استدارة العناصر'),
        ),
    ]
