# Generated by Django 5.2.16 on 2026-07-16 22:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_initial'),
        ('subscribers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المهمة')),
                ('task_type', models.CharField(choices=[('router_installation', 'تركيب راوتر'), ('maintenance', 'صيانة'), ('repair', 'إصلاح'), ('other', 'مهمة أخرى')], default='other', max_length=30, verbose_name='نوع المهمة')),
                ('description', models.TextField(blank=True, verbose_name='تفاصيل المهمة')),
                ('scheduled_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ التنفيذ')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='وقت التنفيذ')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('location', models.CharField(blank=True, max_length=250, verbose_name='الموقع')),
                ('completion_notes', models.TextField(blank=True, verbose_name='ملاحظات الإنجاز')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإنجاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_daily_tasks', to=settings.AUTH_USER_MODEL, verbose_name='مسندة إلى')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_tasks', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_tasks', to='devices.device', verbose_name='الجهاز')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_tasks', to='subscribers.subscriber', verbose_name='المشترك')),
            ],
            options={
                'verbose_name': 'مهمة يومية',
                'verbose_name_plural': 'المهام اليومية',
                'ordering': ['scheduled_date', 'scheduled_time', '-created_at'],
                'indexes': [models.Index(fields=['scheduled_date', 'status'], name='daily_tasks_schedul_c9fde2_idx')],
            },
        ),
    ]
