# Generated by Django 5.2.16 on 2026-07-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الأصل')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='الرقم التسلسلي')),
                ('assignment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإرجاع')),
                ('status', models.CharField(choices=[('available', 'متاح'), ('assigned', 'مُسلّم'), ('returned', 'مُسترجع'), ('damaged', 'تالف')], default='available', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'أصل',
                'verbose_name_plural': 'الأصول',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
            ],
            options={
                'verbose_name': 'فئة أصل',
                'verbose_name_plural': 'فئات الأصول',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assigned', 'تسليم'), ('returned', 'إرجاع'), ('damaged', 'تلف'), ('repaired', 'إصلاح')], max_length=20, verbose_name='الإجراء')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'سجل أصل',
                'verbose_name_plural': 'سجلات الأصول',
                'ordering': ['-date'],
            },
        ),
    ]
