# Generated by Django 5.2.16 on 2026-07-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=30, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('service', models.CharField(choices=[('websites', 'تصميم وتطوير المواقع'), ('custom_software', 'الأنظمة والبرامج المخصصة'), ('networks', 'شبكات الإنترنت'), ('cloud', 'الخوادم والحوسبة السحابية'), ('support', 'الدعم الفني والصيانة'), ('security', 'الأمن السيبراني'), ('marketing', 'التسويق الرقمي'), ('consulting', 'الاستشارات التقنية'), ('other', 'أخرى')], max_length=40, verbose_name='نوع الخدمة')),
                ('message', models.TextField(verbose_name='تفاصيل الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('is_handled', models.BooleanField(default=False, verbose_name='تمت المتابعة')),
            ],
            options={
                'verbose_name': 'طلب تواصل',
                'verbose_name_plural': 'طلبات التواصل',
                'ordering': ['-created_at'],
            },
        ),
    ]
